version: "3.7"
services:
  blog:
    image: hugomods/hugo
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src/pirate.baby
    entrypoint: /bin/sh ./startup.sh
    command: serve