baseURL = 'https://pirate.baby/'
languageCode = 'en-us'
title = 'the Pirate Baby'
theme = ['hugo-shortcode-roneo-collection', 'PaperMod']
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true
googleAnalytics = 'G-QYLKP2XXPB'
disqusShortname = 'https-pirate-baby'

[pagination]
  pagerSize = 5

[taxonomies]
  tag = 'tags'

[outputs]
  home = ['HTML','RSS', 'JSON']

[params]
  comments = true
  env = 'production'
  hideSummary = true
  description = 'Data Engineering and Machine Learning Consulting'
  defaultTheme = 'auto'
  ShowReadingTime = true
  displayFullLangName = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = false
  ShareButtons = ["linkedin","x","facebook","ycombinator","reddit"]
  ShowShareButtons = true

[params.homeInfoParams]
  Title = '_Ship Mercilessly_ :pirate_flag:'
  Content = '''
  [:brain: **AI**](/tags/ai) :black_medium_small_square:
  [:chart_with_upwards_trend: **DE**](/tags/de) :black_medium_small_square:
  [:robot: **ML**](/tags/ml) :black_medium_small_square:
  [:building_construction: **Infra**](/tags/infra) :black_medium_small_square:
  [:computer: **Ops**](/tags/ops)

  {{< box info >}}
  The future of software is <b>[software that builds itself](/generative-driven-design)</b>.<br/>
  Want to forge the code of tomorrow with us? <u>[find out more](/gdd-interest-form)</u>.
  {{</box>}}
  '''

[[params.SocialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/company/pirate-baby'

[[params.SocialIcons]]
  name = 'github'
  url = 'https://github.com/pirate-baby'

[[params.SocialIcons]]
  name = 'medium'
  url = 'https://medium.com/@ethan.m.knox'

[[params.SocialIcons]]
  name = 'email'
  url = 'mailto:ethan@pirate.baby'


[params.label]
  icon = "/piratebaby.png"
  iconHeight = 40

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true